name: Generate Snake

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: Vitor-Izidoro
          output: out/snake.svg

      - name: Commit and push
        run: |
          git add out/snake.svg
          git commit -m "Generated Snake"
          git push
